# Generated by Django 3.2.9 on 2021-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0004_alter_currency_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
    ]
